nome : Waka Readme

on :
   workflow_dispatch :
   schedule :
     # Viene eseguito alle 00:00 UTC 
    - cron : " 0 0 * * * "

job :
   update-readme :
     name : aggiorna il README di questo repository 
    run-on : ubuntu-latest 
    steps :
      - usa : athul/waka-readme@master 
        con :
           WAKATIME_API_KEY : ${{ secrets.WAKATIME_API_KEY }}
